### ISSUE TITLE
Changing operation messes up calculation display

### ISSUE THREAD

**Issue by jasninus** [mwnDK1402/calculator-js#1]
Look at [GIF](https://i.imgur.com/UnWfFnP.gifv) for video demonstrating bug.

**Comment by mwnDK1402** [comment]
A test has been created. Fixing it will require a rewrite of the operation system. Will rewrite the operation system soon.

**Comment by mwnDK1402** [comment]
The operation system has been rewritten, and the bug has been fixed.
